-- Determine the top 3 most ordered pizza types based on revenue for each pizza category

-- Step 1: Calculate revenue generated by each individual pizza

WITH pizza_revenue AS (
    SELECT 
        pt.category,
        pt.pizza_name,
        SUM(od.quantity * p.price) AS revenue
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt ON p.pizza_type = pt.pizza_type_id
    GROUP BY pt.category, pt.pizza_name
),

-- Step 2: Rank pizzas within each category based on revenue (highest first)

ranked_pizzas AS (
    SELECT *,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) AS `rank`
    FROM pizza_revenue
)


-- Step 3: Select the top 3 pizzas by revenue within each category

SELECT 
    category,
    pizza_name,
    ROUND(revenue, 2) AS revenue
FROM ranked_pizzas
WHERE `rank` <= 3
ORDER BY category, `rank`;
